package interfaz;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.border.*;
import fis_propina.FIS_Propina;

/**
 *
 * @author amomo
 */
public class PropinaUI extends javax.swing.JFrame {

    FIS_Propina resultados = new FIS_Propina();

    /**
     * Creates new form PropinaUI
     */
    public PropinaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jPanel1 = new JPanel();
        iconoLabel = new JLabel();
        bannerLabel = new JLabel();
        msj1Label = new JLabel();
        msj2Label = new JLabel();
        comidaLabel = new JLabel();
        comidaTextField = new JTextField();
        calcularButton = new JButton();
        jScrollPane1 = new JScrollPane();
        resultadoTextArea = new JTextArea();
        comidaLabel2 = new JLabel();
        comidaTextField2 = new JTextField();
        comidaLabel3 = new JLabel();
        comidaTextField3 = new JTextField();
        comidaLabel4 = new JLabel();
        comidaTextField4 = new JTextField();
        comidaLabel5 = new JLabel();
        comidaTextField5 = new JTextField();
        salirButton = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        var contentPane = getContentPane();

        //======== jPanel1 ========
        {
            jPanel1.setBorder(new TitledBorder("Calcula la propina"));

            //---- iconoLabel ----
            iconoLabel.setIcon(new ImageIcon(getClass().getResource("/recursos/imagen.png")));
            iconoLabel.setText("jLabel1");

            //---- bannerLabel ----
            bannerLabel.setFont(new Font("Impact", Font.BOLD, 48));
            bannerLabel.setForeground(new Color(0, 153, 204));
            bannerLabel.setText("Hidroponia-FIS");

            //---- msj1Label ----
            msj1Label.setText("Califique de cero a diez (siendo cero de lo peorcito y diez espectacular),");

            //---- msj2Label ----
            msj2Label.setText("la calidad del servicio y la comida:");

            //---- comidaLabel ----
            comidaLabel.setText("Color de la planta:");

            //---- comidaTextField ----
            comidaTextField.addActionListener(e -> comidaTextFieldActionPerformed(e));
            comidaTextField.addKeyListener(new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {
                    comidaTextFieldKeyTyped(e);
                }
            });

            //---- calcularButton ----
            calcularButton.setText("Calcular");
            calcularButton.addActionListener(e -> calcularButtonActionPerformed(e));

            //======== jScrollPane1 ========
            {

                //---- resultadoTextArea ----
                resultadoTextArea.setEditable(false);
                resultadoTextArea.setColumns(20);
                resultadoTextArea.setRows(5);
                jScrollPane1.setViewportView(resultadoTextArea);
            }

            //---- comidaLabel2 ----
            comidaLabel2.setText("Humedad:");

            //---- comidaTextField2 ----
            comidaTextField2.addActionListener(e -> comidaTextFieldActionPerformed(e));
            comidaTextField2.addKeyListener(new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {
                    comidaTextFieldKeyTyped(e);
                }
            });

            //---- comidaLabel3 ----
            comidaLabel3.setText("Temperatura:");

            //---- comidaTextField3 ----
            comidaTextField3.addActionListener(e -> comidaTextFieldActionPerformed(e));
            comidaTextField3.addKeyListener(new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {
                    comidaTextFieldKeyTyped(e);
                }
            });

            //---- comidaLabel4 ----
            comidaLabel4.setText("Radiacion solar:");

            //---- comidaTextField4 ----
            comidaTextField4.addActionListener(e -> comidaTextFieldActionPerformed(e));
            comidaTextField4.addKeyListener(new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {
                    comidaTextFieldKeyTyped(e);
                }
            });

            //---- comidaLabel5 ----
            comidaLabel5.setText("Concentracion de nutrientes y minerales:");

            //---- comidaTextField5 ----
            comidaTextField5.addActionListener(e -> comidaTextFieldActionPerformed(e));
            comidaTextField5.addKeyListener(new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {
                    comidaTextFieldKeyTyped(e);
                }
            });

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(iconoLabel, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bannerLabel)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(msj1Label, GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(msj2Label, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comidaLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(comidaTextField4, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 284, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comidaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(comidaTextField, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comidaLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(comidaTextField2, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comidaLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(comidaTextField3, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comidaLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(comidaTextField5, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(calcularButton)))
                        .addContainerGap(178, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(iconoLabel, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(bannerLabel)))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(msj1Label)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msj2Label)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(comidaLabel)
                            .addComponent(comidaTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(comidaLabel2))
                            .addComponent(comidaTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(comidaLabel3))
                            .addComponent(comidaTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(comidaTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(comidaLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(comidaLabel5))
                            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(comidaTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(calcularButton)))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addContainerGap())
            );
        }

        //---- salirButton ----
        salirButton.setText("Salir");
        salirButton.addActionListener(e -> salirButtonActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(salirButton)))
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salirButton)
                    .addGap(15, 15, 15))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }

    private void comidaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void comidaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {

        char validar = evt.getKeyChar();

        if(Character.isLetter(validar)){

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Valor inválido. Ingrese solo números");
        }
    }

    private void calcularButtonActionPerformed(java.awt.event.ActionEvent evt) {

        double color = Double.parseDouble(comidaTextField.getText().replace(",", "."));
        double humedad = Double.parseDouble(comidaTextField2.getText().replace(",", "."));
        double temperatura = Double.parseDouble(comidaTextField3.getText().replace(",", "."));
        double radiacion = Double.parseDouble(comidaTextField4.getText().replace(",", "."));
        double concentracion = Double.parseDouble(comidaTextField5.getText().replace(",", "."));
//        System.out.println(color + " " + humedad + " " + temperatura + " " + radiacion + " " + nutriententes);
//        Integer servicio = 5;

        resultadoTextArea.setText(resultados.calcularPropina(color,humedad,temperatura,radiacion,concentracion));
    }

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PropinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PropinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PropinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PropinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PropinaUI().setVisible(true);
            }
        });
    }


    private JPanel jPanel1;
    private JLabel iconoLabel;
    private JLabel bannerLabel;
    private JLabel msj1Label;
    private JLabel msj2Label;
    private JLabel comidaLabel;
    private JTextField comidaTextField;
    private JButton calcularButton;
    private JScrollPane jScrollPane1;
    private JTextArea resultadoTextArea;
    private JLabel comidaLabel2;
    private JTextField comidaTextField2;
    private JLabel comidaLabel3;
    private JTextField comidaTextField3;
    private JLabel comidaLabel4;
    private JTextField comidaTextField4;
    private JLabel comidaLabel5;
    private JTextField comidaTextField5;
    private JButton salirButton;
}